language: julia

os:
    - linux
    - osx

julia:
    - 0.7
    - 1.0
    - nightly

matrix:
    allow_failures:
        - julia: nightly

addons:
    apt:
        packages:
            - hdf5-tools
    homebrew:
        packages:
            - hdf5

jobs:
    include:
        - stage: "Documentation"
          os: linux
          script:
            - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
            - julia --project=docs/ docs/make.jl
          after_success:
            - julia --project=docs/ docs/deploy.jl

after_success:
    - julia -e 'cd(Pkg.dir("AsterReader")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
