name = "AsterReader"
uuid = "cb1a753d-6b7b-52e3-9bfe-57d99d445c39"
authors = ["Jukka Aho <ahojukka5@gmail.com>"]
version = "0.2.3"

[deps]
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"

[compat]
julia = "≥ 1.0"
